# Generated by Django 4.2.6 on 2023-10-28 22:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('unzipped_path', models.CharField(default=pathlib.PurePosixPath('/home/alisher/PycharmProjects/pfo_hackathon/gangup_up/backend/media/empty'), max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_id', models.TextField(default='task_id', max_length=1024)),
                ('status', models.CharField(default='PENDING', max_length=256)),
                ('task_type', models.CharField(default='unzip', max_length=256)),
                ('input_file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.archivemodel')),
            ],
        ),
    ]
