# Generated by Django 4.2.6 on 2023-10-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivemodel',
            name='unzipped_path',
            field=models.CharField(default='/home/alisher/PycharmProjects/pfo_hackathon/gangup_up/backend/media/empty/', max_length=1024),
        ),
    ]
