# Generated by Django 4.2.6 on 2023-10-28 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_archivemodel_unzipped_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='input_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.archivemodel'),
        ),
    ]
