# Generated by Django 4.2.6 on 2023-10-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_taskmodel_input_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivemodel',
            name='show_rgb',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='archivemodel',
            name='show_tiff',
            field=models.BooleanField(default=False),
        ),
    ]
